substitutions:
  _REGION: us-central1
  _AR_REPO: web
  _SERVICE: web
steps:
- name: gcr.io/cloud-builders/docker
  args: ["build","-f","Containerfile","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/next:$COMMIT_SHA","."]
- name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/next:$COMMIT_SHA"]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    ["gcloud","run","deploy","${_SERVICE}",
     "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/next:$COMMIT_SHA",
     "--region","${_REGION}",
     "--platform","managed",
     "--port","8080",
     "--allow-unauthenticated",
     "--set-env-vars","NEXT_PUBLIC_SITE_URL=https://ampruitt.com"]
images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/next:$COMMIT_SHA"
